server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie

spring:
  application:
    name: react_crud
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: "123"
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pack.dto.**